### ISSUE TITLE
Update To Client 2.0

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/arc.react#54]
https://github.com/daostack/client/tree/client-2-0

**Comment by dOrgJelli** [comment]
Some thoughts from a chat with @cbrzn 

```
<DAO address="0xMY_DAO">

  // 1. proposals for specific type of plugin
  <CompetitionPlugin>
    <Proposals from="Competition">
      <CompetitionProposal.Data>
      {(data: CompetitionProposalData) => {

      }}
      </CompetitionProposal.Data>
    </Proposals>
  </CompetitionPlugin>

  // 2. all plugins and all proposals
  <Plugins from="DAO">
    <Proposals from="Plugin">
      <Proposal.Data>
      {(proposal: ProposalData) => {
        switch (proposal.type) {
          case "Competition":
            return <CompetitionProposal proposal={proposal as CompetitionProposalData} />
            break;
        }
      }}
      </Proposal.Data>
    </Proposals>
  </Plugins>

  <Plugins>
    <PluginSelector type="PluginManager" render={() => (
      
    )} />
    <Proposals from="Plugin">
      <ProposalSelector type="Competition" render={() => (

      )}>
    </Proposals>
  </Plugins>

</DAO>
```

**Comment by cbrzn** [comment]
Changes to do:
- We are no longer using `.state`, instead we are using `.fetchState`
- Create react component for every implemented plugin in `arc.js` library, they will live in `plugins` folder, with `Plugins.tsx` and `PluginBase.tsx`

**Comment by dOrgJelli** [comment]
> We are no longer using `.state`, instead we are using `.fetchState`

After thinking about this more, I think we'll want to be a bit more deliberate about how we do this in order to:
1. Return "prefetched" data that's stored in the entity's `coreState` property
2. Support subscribing to data changes, which will in return trigger react rerenders when the data changes. For example: if a proposal gets voted on while you're viewing it, a `<Proposal.Data>` should rerender because the underlying data is changed.

Number 2 is happening in the current implementation, because we use a `state()` subscription. # 1 is not.

So in order to upgrade to 2.0, I think we should do the following:
1. Return coreState, if it isn't undefined, before we open the subscription with state().
2. Add an optional prop for users to disable subscriptions. Maybe call it `noSub`: `<Proposal noSub>`
